#!/bin/sh
echo "****************************************"
echo "*   TvToM3uPanel Plugin installed      *"
echo "*                                      *"
echo "*  CorvoBoys Team                      *"
echo "*  Enjoy our plugin                    *"
echo "****************************************"
echo "Restarting Enigma2 to load..."
exit 0
