#!/bin/sh
echo "****************************************"
echo "*   TvToM3uPanel Plugin installed      *"
echo "*                                      *"
echo "*  CorvoBoys Team                      *"
echo "*  Enjoy our plugin                    *"
echo "****************************************"
echo "Restarting Enigma2 to load..."
# init 4
# killall -9 enigma2 > /dev/null 2>&1
# init 3
exit 0
