#!/bin/sh
echo "Checking for an older version of TvToM3u in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/TvToM3uPanel ]
then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/TvToM3uPanel > /dev/null 2>&1
echo "An older version of TvToM3u was found and removed"
echo "Proceeding to installation..."
else
echo "TvToM3uPanel  was not found in the system"
echo "Proceeding to installation..."
fi
exit 0
